#!/usr/bin/env python3
"""Render docs/*.md into static HTML at the repo root.

    pip install markdown pygments
    python3 build.py

Output is committed, so the site works without a build step on GitHub Pages.
"""

import html
import pathlib
import re

import markdown
from pygments.formatters import HtmlFormatter

ROOT = pathlib.Path(__file__).parent
DOCS = ROOT / "docs"
ASSETS = ROOT / "assets"

SITE_TITLE = "Value set library"
SITE_TAGLINE = "Reusable, versioned code lists for claims research"

# slug, source, nav label, output file
PAGES = [
    ("index", "index.md", "Overview", "index.html"),
    ("process", "process.md", "Process", "process.html"),
    ("governance", "governance.md", "Governance", "governance.html"),
    ("project-instructions", "project-instructions.md",
     "Project instructions", "project-instructions.html"),
    ("project-context", "project-context.md",
     "Project context", "project-context.html"),
]

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="stylesheet" href="assets/style.css">
<link rel="stylesheet" href="assets/highlight.css">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='13' font-size='14'>&#128203;</text></svg>">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<div class="layout">
<header class="sidebar">
  <div class="brand">
    <a href="index.html">{site_title}</a>
    <p>{site_tagline}</p>
  </div>
  <nav class="site-nav" aria-label="Site">
    <ul>
{site_nav}
    </ul>
  </nav>
{page_toc}
</header>
<main id="main">
  <article class="prose">
{content}
  </article>
  <footer class="page-footer">
    <p>Source: <code>docs/{source}</code> &middot; rebuild with <code>python3 build.py</code></p>
  </footer>
</main>
</div>
</body>
</html>
"""


def flatten(tokens):
    """toc_tokens is a tree; walk it depth-first."""
    for t in tokens:
        yield t
        yield from flatten(t.get("children", []))


def build_toc(toc_tokens):
    """Sidebar 'on this page' list, h2 only."""
    items = [t for t in flatten(toc_tokens) if t["level"] == 2]
    if len(items) < 2:
        return ""
    lis = "\n".join(
        '      <li><a href="#{id}">{name}</a></li>'.format(
            id=t["id"], name=html.escape(t["name"]))
        for t in items
    )
    return (
        '  <nav class="page-toc" aria-label="On this page">\n'
        "    <h2>On this page</h2>\n"
        "    <ul>\n" + lis + "\n    </ul>\n  </nav>\n"
    )


def first_paragraph(text):
    """Crude meta description: first non-heading, non-blank line."""
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith(("#", "-", "|", "`", "<")):
            return html.escape(re.sub(r"[*`\[\]]", "", line))[:180]
    return SITE_TAGLINE


def main():
    ASSETS.mkdir(exist_ok=True)

    # Pygments themes: light by default, dark under prefers-color-scheme.
    light = HtmlFormatter(style="friendly").get_style_defs(".codehilite")
    dark = HtmlFormatter(style="stata-dark").get_style_defs(".codehilite")
    dark = "\n".join("  " + ln for ln in dark.splitlines())
    (ASSETS / "highlight.css").write_text(
        "/* GENERATED by build.py — do not edit */\n"
        + light
        + "\n@media (prefers-color-scheme: dark) {\n"
        + dark
        + "\n}\n",
        encoding="utf-8",
    )

    for slug, source, _label, outfile in PAGES:
        text = (DOCS / source).read_text(encoding="utf-8")

        md = markdown.Markdown(
            extensions=["extra", "codehilite", "toc", "sane_lists", "admonition"],
            extension_configs={
                "codehilite": {"guess_lang": False, "linenums": False},
                "toc": {"permalink": "#", "permalink_title": "Link to this section"},
            },
        )
        content = md.convert(text)
        # Wide tables get their own scroll container so the page body never
        # scrolls horizontally on a phone.
        content = content.replace("<table>", '<div class="table-scroll"><table>')
        content = content.replace("</table>", "</table></div>")

        nav = []
        for s, _src, label, out in PAGES:
            current = ' class="current" aria-current="page"' if s == slug else ""
            nav.append(
                '      <li><a href="{out}"{cur}>{label}</a></li>'.format(
                    out=out, cur=current, label=html.escape(label))
            )

        h1 = re.search(r"^#\s+(.+)$", text, re.M)
        page_title = h1.group(1).strip() if h1 else slug
        title = page_title if slug == "index" else f"{page_title} — {SITE_TITLE}"

        (ROOT / outfile).write_text(
            TEMPLATE.format(
                title=html.escape(title),
                description=first_paragraph(text),
                site_title=html.escape(SITE_TITLE),
                site_tagline=html.escape(SITE_TAGLINE),
                site_nav="\n".join(nav),
                page_toc=build_toc(md.toc_tokens),
                content=content,
                source=source,
            ),
            encoding="utf-8",
        )
        print(f"wrote {outfile}")


if __name__ == "__main__":
    main()
